baseurl = "https://blog.kevsecurity.org/"
title = "Kevinlpd security blog"
author = "@Kev"
copyright = "Copyright Â© Kev"
canonifyurls = true
paginate = 10

theme = "hugo-blog-jeffprod"

[taxonomies]
    tag = "tags"
    archive = "archives"
	category = "categories"
[params]
	description = "Winter is comming"
	twitter = "kvin_lpd"
	github = "kevin-ksis"

